### ISSUE TITLE
非常感谢

### ISSUE THREAD

**Issue by zousandian** [fraserxu/intro-to-react#1]
官网上有些看不懂的，看了一下你的教程就明白了。
非常感谢～

**Comment by fraserxu** [comment]
哈哈哈， 好就给star啊！

**Comment by zousandian** [comment]
@fraserxu star 了啦。期待更新～
对了，http://fraserxu.me/intro-to-react/render-method/ 这个页面例子有地方重叠了

**Comment by fraserxu** [comment]
那个教程还是针对很早之前版本的react, 现在0.13的改动很大，有时间我会更新的！

**Comment by zousandian** [comment]
thx~~ :clap:
